### ISSUE TITLE
Problem when sending GET-request

### ISSUE THREAD

**Issue by PatBateman76** [kamranayub/azure-storage-rest-postman#2]
Postman just reports: "There was an error in evaluating the Pre-request Script:  TypeError: Cannot read property 'toString' of undefined"

I have setup all the variables needed

**Comment by kamranayub** [comment]
Fixed in https://github.com/kamranayub/azure-storage-rest-postman/commit/11e0cf6d018fb24de1bb693a386b0dca0bedd0e9

Thanks for reporting this!
